### PR TITLE
create DB models for comments and flags

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony @smn ready for review.

Explanation: I can't use SQLAlchemy's ORM. So I wrote the `RowObjectMixin` class to keep common row operations DRY. It's not using deferreds at the moment - I'll add them when I have a clearer idea of what I'm doing.

**Comment by smn** [comment]
Sorry, it really does need to be async / deferreds, it's really hard to go back otherwise.

**Comment by smn** [comment]
@Rizziepit it's probably worth chatting to @jerith about https://pypi.python.org/pypi/alchimia

**Comment by Rizziepit** [comment]
@smn @miltontony all the bits that touch the database are async now. I've also switched from pytest to trial.

**Comment by miltontony** [comment]
:+1:  once travis ;)

**Pull request merged**
