### PR TITLE
include error codes or all errors

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony @smn ready for review. I made sure all errors return the same fields. The important bit: the `error_code` field contains text like `USER_BANNED` or `STREAM_NOT_OPEN` to help the client distinguish between errors with the same HTTP status code.

**Comment by smn** [comment]
:+1: but you're going to have to explain to me at some point how we're using both Werkzeug (sync afaik?) and Klein (async)?

**Comment by Rizziepit** [comment]
Klein is built on Werkzeug. It doesn't use all of Werkzeug though. Just routing and exceptions afaik.

**Comment by smn** [comment]
oh sweet!

**Pull request merged**
